import Link from 'next/link'
import { prisma } from '@/lib/prisma'
import { currentUser } from '@/lib/session'
import { getEntitlements } from '@/lib/access'
import { canAccessChapter } from '@/lib/access'
import { DoubtTool, FormulaSheetTool, PracticeTool } from './ToolPanels'

export default async function ToolsPage() {
  const user = await currentUser()
  if (!user) {
    return (
      <div className="mx-auto max-w-md rounded-3xl card-surface px-8 py-12 text-center">
        <h1 className="text-2xl font-extrabold text-navy-deep">Sign in to use the tools</h1>
        <p className="mt-2 font-semibold text-navy/55">Each one costs a daily AI credit.</p>
        <Link
          href="/login"
          className="mt-6 inline-block rounded-full flame-gradient px-7 py-3 font-extrabold text-white"
        >
          Sign in
        </Link>
      </div>
    )
  }

  // Offer only chapters this student can actually open — the same rule the
  // server actions re-check before spending a credit.
  const courses = await prisma.course.findMany({
    where: user.classLevelId ? { classLevelId: user.classLevelId } : {},
    orderBy: { sortKey: 'asc' },
    include: {
      subject: true,
      chapters: { orderBy: { index: 'asc' } },
    },
  })

  const ent = await getEntitlements(user.id)
  const chapters = courses.flatMap((c) =>
    c.chapters
      .filter((ch) => canAccessChapter(ch, c, ent))
      .map((ch) => ({ id: ch.id, label: `${c.subject.name} · Ch ${ch.index}: ${ch.title}` })),
  )

  if (chapters.length === 0) {
    return (
      <div className="space-y-5">
        <h1 className="text-3xl font-extrabold text-navy-deep">Tools</h1>
        <p className="rounded-3xl card-surface px-6 py-10 text-center font-semibold text-navy/50">
          No chapters are available for your class yet.{' '}
          <Link href="/academic" className="font-extrabold text-ember hover:underline">
            Browse the catalog →
          </Link>
        </p>
      </div>
    )
  }

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-3xl font-extrabold text-navy-deep">Tools</h1>
        <p className="mt-1 font-semibold text-navy/50">
          Each generation costs one AI credit. You have{' '}
          <strong className="text-navy-deep">{user.dailyCredits}</strong> left today.
        </p>
      </div>

      <FormulaSheetTool chapters={chapters} />
      <PracticeTool chapters={chapters} />
      <DoubtTool chapters={chapters} />

      <p className="rounded-2xl bg-navy/5 px-5 py-4 text-sm font-semibold text-navy/55">
        These are generated by AI and can contain mistakes. Check anything you plan to rely on against
        your textbook.
      </p>
    </div>
  )
}
